### ISSUE TITLE
Request Android and iOS example that picks from system contacts

### ISSUE THREAD

**Issue by esutton** [lodev09/react-native-cell-components#1]
Very nice!  I will be following this project's progress!

Thank you for sharing your work.

**Comment by lodev09** [comment]
Thanks @esutton. About your request, there's no contacts API provided by react native yet so I'm afraid you'd have to play it on your end using [3rd party packages](https://github.com/rt2zz/react-native-contacts) that supports contacts.

Just populate `this._usersData` with your contacts collection, it should work :)
