### ISSUE TITLE
Identifier 'isIphoneX' has already been declared

### ISSUE THREAD

**Issue by akhilsanker** [lodev09/react-native-cell-components#12]
Getting 'Identifier 'isIphoneX' has already been declared' in theme.js file while react-native run-ios.

Environment:
     "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-cell-components": "^0.4.4",
     react-native-cli: 2.0.1
Thanks

**Comment by lodev09** [comment]
update package to `0.5`
https://www.npmjs.com/package/react-native-cell-components

was fixed [here](https://github.com/lodev09/react-native-cell-components/pull/11)
