### ISSUE TITLE
Text Input cell and datepicker cell also goes white? plus UseNativeDriver is not defined.

### ISSUE THREAD

**Issue by dlogvin** [lodev09/react-native-cell-components#16]
How is it possible to prevent this? I cannot find a way to fix this. I attach screenshots taken from the simulator (same errors happen in the physical device).

![Simulator Screen Shot - iPhone 11 - 2020-07-27 at 12 09 21](https://user-images.githubusercontent.com/62754263/88524658-4f780880-d002-11ea-8876-8478cff207c2.png)

**Comment by lodev09** [comment]
Haven't looked at it but try to disable dark mode and see if that works.
For the useNativeDriver issue, uncomment this line:
https://github.com/lodev09/react-native-cell-components/blob/52f168a59a1f748d7844e411a87aa578ac87f5cb/components/ActionSheet.js#L76

**Comment by dlogvin** [comment]
It works if I disable dark mode, but I cannot rely on the users for them to disable dark mode just to use my app... is it possible to somehow add some support to prevent this from happening if the dark mode is activated?

**Comment by lodev09** [comment]
@danslabs there is a way in your app config to not support dark mode. Regarding the component support of it, I don't have time to do it yet -- you could give it a try and submit a PR :)

**Comment by dlogvin** [comment]
I'll try to add the support for darkmode and proceed with the PR. But on the mean time, how is it possible to not allow dark mode on the app?

**Comment by lodev09** [comment]
@danslabs Did a quick google and found this: https://stackoverflow.com/a/56546554/3685987

**Comment by dlogvin** [comment]
Thank you :)
