### ISSUE TITLE
CellGroup: Header only accepts String

### ISSUE THREAD

**Issue by ghost** [lodev09/react-native-cell-components#3]
Per the CellGroup code, this.props.header can be an OBJECT or a String value. However, when you pass in an object or custom View (essentially), an error shows; "this.props.header.toUpperCase is not a function. 

I'm assuming the the switch should be doing a typeof on the header so it will fall into the first case rather than the default, which cause this error.

switch(typeof this.props.header)
     case "object":
          return this.props.header
          break;
     default:
          return (<View>.......</View>)

**Comment by lodev09** [comment]
was definitely a bug. thanks for reporting @DarthFowla :)
