### ISSUE TITLE
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! 

### ISSUE THREAD

**Issue by sirhu11** [lodev09/react-native-cell-components#9]
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')
//貌似是注释问题
CellGroup，如果header===“”的时候，会报错
renderHeader() {
    switch (typeof this.props.header) {
      case 'object':
        return this.props.header;
        break;
      default:
        return (
          <View style={styles.header} >
            {
              this.props.header &&
              <Text style={styles.headerText} >{this.props.header.toUpperCase()}</Text>
            }
          </View>
        );
    }
  }

ref:https://github.com/facebook/react-native/issues/18880
Here is another fun one that happens only in android (even in RN 0.55.3):

{this.props.loadingURL&& <View style={{flexDirection:‘row’,alignItems:‘center’,justifyContent:‘center’,marginTop:40,marginBottom:10,}}> <Text style={{marginRight:10,fontSize:20}}>{this.props.loadingURL}</Text> <ActivityIndicator size=“large” color=“black” /> </View> }

This blows up Android with that error if loadingURL is an empty string. It works fine if it's a non-empty string or a boolean or if I change it to this (basically convert it to a boolean):

{!_.isEmpty(this.props.loadingURL)&&

**Comment by lodev09** [comment]
I don’t see this issue on my end. Feel free to provide more info on how I can replicate this issue
